# Identity API - Base Service
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: cryptojackpot
  labels:
    app: identity-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: identity-api
