# Secrets for QA - MongoDB (Atlas)
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: cryptojackpot
type: Opaque
stringData:
  MONGODB_ROOT_USERNAME: "admin"
  MONGODB_ROOT_PASSWORD: "REPLACE_WITH_ATLAS_PASSWORD"
  MONGODB_AUDIT_CONNECTION: "mongodb+srv://admin:REPLACE@qa-cluster.mongodb.net/cryptojackpot_audit?retryWrites=true&w=majority"
  MONGODB_AUDIT_DATABASE: "cryptojackpot_audit"
