# Winner API - Base Service
apiVersion: v1
kind: Service
metadata:
  name: winner-api
  namespace: cryptojackpot
  labels:
    app: winner-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: winner-api
