# Secrets for LOCAL - Brevo (Email)
# Usado por: Notification API
apiVersion: v1
kind: Secret
metadata:
  name: brevo-secrets
  namespace: cryptojackpot
type: Opaque
stringData:
  # API Key de Brevo - usada por Notification API
  BREVO_API_KEY: "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"
  BREVO_SENDER_EMAIL: "lfmiguel16@gmail.com"
  BREVO_SENDER_NAME: "CryptoJackpot"
  BREVO_BASE_URL: "http://localhost:3000"

